name: Sync Docker Images

#on:
#  push:
#    paths:
#      - images-list
on:
  push:
    branches:
      - master  # 或者指定你想要的分支

jobs:
  sync-images:
    runs-on: ubuntu-latest

    outputs:
      images: ${{ steps.read-images.outputs.images }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read image list
        id: read-images
        run: |
          images=$(jq -R -s -c 'split("\n")[:-1]' < images-list)
          echo "images=$images" >> $GITHUB_ENV
          echo "images=$images" >> $GITHUB_OUTPUT
          echo "Images: $images"

  sync-image:
    needs: sync-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.sync-images.outputs.images) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_user_name }}
          password: ${{ secrets.docker_password }}

      - name: Log in to Qingyun Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.target_registry_username }}
          password: ${{ secrets.target_registry_password }}
          registry: ${{ secrets.target_registry_url }}

      - name: Sync image
        run: |
          image="${{ matrix.image }}"
          docker pull "$image"
          target_image="${{ secrets.target_registry_url }}/$(basename "$image")"
          docker tag "$image" "$target_image"
          docker push "$target_image"